#! /bin/bash
# Rolf Niepraschk (Rolf.Niepraschk@ptb.de), 2020-05-26

# Preparation and start of the relayServer process.

R_PATH=/usr/local/share/relayServer/  # Path to relayServer installation

dist=$(lsb_release -is | cut -d " " -f 1 | tr '[A-Z]' '[a-z]')

case "$dist" in
  opensuse)   
    chown -R nobody:nobody ${R_PATH} ;;
  ubuntu|raspbian|debian)
    chown -R nobody:nogroup ${R_PATH} ;;
esac

cd ${R_PATH}
ln -sf $PWD/vlLogging /usr/local/bin/vlLogging
systemctl daemon-reload                        # if already running 
systemctl link $PWD/relayServer.service
systemctl restart relayServer.service
systemctl enable relayServer.service
systemctl status relayServer.service

exit

