#! /bin/bash
# Rolf Niepraschk (Rolf.Niepraschk@ptb.de), 2020-05-26

# Preparation and start of the relayServer process.

R_PATH=/usr/local/share/relayServer/  # Path to relayServer installation

cd ${R_PATH}
ln -sf $PWD/vlLogging /usr/local/bin/vlLogging
systemctl daemon-reload                        # if already exist 
systemctl link $PWD/relayServer.service
systemctl restart relayServer.service
systemctl enable relayServer.service
systemctl status relayServer.service

exit

