#! /bin/bash
# see: https://coderwall.com/p/mk18zq/automatic-git-version-tagging-for-npm-modules

version=$(git diff HEAD^..HEAD -- \
  "$(git rev-parse --show-toplevel)"/package.json | \
  grep '^\+.*version' | sed -s 's/[^0-9\.]//g')

if [ "$version" != "" ]; then
  git tag -a "v$version" -m "`git log -1 --format=%s`"
  echo "Created a new tag, v$version"
  git checkout production
  git merge master
  git push origin production && git push origin production --tags
  git checkout master
fi
