#!/bin/bash

# Rolf Niepraschk, Rolf.Niepraschk@ptb.de, 2016-04-15

# Stopt den relayServer-Dämon-Prozess und ruft das Script "relayServer.js"
# direkt auf, um ggf. Programmabstürze nicht zu übersehen.

SUDO=''
if (( $EUID != 0 )); then
  SUDO='sudo -E'
fi

$SUDO systemctl stop relayServer.service

$SUDO sudo -E -u wwwrun -g www /usr/bin/node \
  /usr/local/share/relayServer/relayServer.js
