#! /bin/bash
# Rolf Niepraschk (Rolf.Niepraschk@ptb.de), 2017-06-02

# Verteilt relayServer-Dateien zu ausgewählten Rechnern per "rsync" und
# aktiviert den relayServer-Prozess dort.

R_PATH=/usr/local/share/relayServer  # Pfad zu relayServer-Installation 

function doIt {
  echo "Begin: ************** $1 **************"
  rsync --info=STATS1 -azL --delete --keep-dirlinks --exclude '.git'  \
    ${R_PATH} $1:$(dirname $R_PATH)/
  # »-L« – Behandle Symlinks auf dem Quellsystem wie Verzeichnisse.  
  # »--keep-dirlinks« – Behandle Symlinks auf dem Zielsystem wie Verzeichnisse.
  ssh root@$1 ${R_PATH}/install
  echo "End:   ************** $1 **************"
}
 
if [[ $1 ]]; then
  server="$1"
else
  server="a73434 a73435 a75436 e73461 e73462 e75455 e75457 e75458 \
    e75459 e75466 e75467 e75470 i75419 i75420 i75422 i75434 i75436"
# 
  server="a73434 a73435 a75436 e75459 e75466 i75422 i75436"
fi

# Alle Rechner müssen ohne Passwortabfrage per ssh erreichbar sein!

for i in $server; do
  doIt $i
done

exit
