#! /bin/bash
# Rolf Niepraschk (Rolf.Niepraschk@ptb.de)

# Installiert eine neue Version  vom zugehörigen GIT-Repositorium
# und lädt den Server-Prozess neu.

# Aufruf als root (auf dem Server!):
#
# ./update_from_git
#

SCRIPT_DIR="$( dirname -- "$BASH_SOURCE"; )"
if ! [[ ${SCRIPT_DIR} = "." ]]; then
cat <<EOF
  Error: Wrong directory!
  Change to the directory where the script is installed.
EOF
exit -1
fi

PROJECT="relayServer"
THIS_USER=vaclab
THIS_GROUP=""
GIT_USER=vaclab
GITLAB_URL=https://gitlab1.ptb.de/vaclab/${PROJECT}.git

echo '* Update from GIT repository'
THIS_DIR=$(pwd)
pushd . > /dev/null
TEMP_DIR=$(runuser -u ${GIT_USER} -- mktemp -d)
cd ${TEMP_DIR}
runuser -u ${GIT_USER} -- git clone "${GITLAB_URL}" >/dev/null 2>&1
cd ${PROJECT} && rm -rf .git # we don't need the git overhead
rsync -a . ${THIS_DIR}/      # "/" is important
popd > /dev/null
rm -rf ${TEMP_DIR}
chown -R ${THIS_USER}:${THIS_GROUP} ./ 

echo '* Restart the server'
systemctl daemon-reload
systemctl restart ${PROJECT}.service

exit
