#!/bin/bash

# vxiTransceiver
#
# Rolf Niepraschk, 2010-12-13

VXI_BIN=/usr/local/bin/vxi11_transceiver
#VXI_BIN=./vxi11_transceiver

function is_integer() {
    [ "$1" -eq "$1" ] > /dev/null 2>&1
    return $?
}

test $# -ge 3 || exit -1

if is_integer $3; then
  timeout="$3"
  start=3
else 
  timeout="2000"
  start=2
fi

i=0

# vxiTransceiver "e75484.berlin.ptb.de" "COM1,488" " P\n"

for cmd in "$@"; do
  i=$(( i + 1 ))
  if (( "$i" > $start )) ; then
    #echo $VXI_BIN "$1" "$2" "$timeout" "$cmd"
    $VXI_BIN "$1" "$2" "$timeout" "$cmd"
  fi
done

exit 0

